@isTest
public class TestTask2Schedule {

   /*@isTest
    static void testTask2Schedule() {
      
        List<Account> testAccounts = new List<Account>();
        //for (Integer i = 0; i < 5; i++) {
            testAccounts.add(new Account(Name = 'Test Account1 ' + Date.TODAY(), Rating = 'Cold'));
        //}
        insert testAccounts;

        Test.startTest();

       
        Task2Schedule scheduler = new Task2Schedule();
        scheduler.ScheduleJob();

        Test.stopTest();
        List<Account> updatedAccounts = [SELECT Id, Rating FROM Account WHERE Rating = 'Warm'];

        System.assertEquals(5, updatedAccounts.size(), 'Expected 5 Accounts to be updated to Warm');

        for (Account acc : updatedAccounts) {
            System.assertEquals('Warm', acc.Rating, 'Account Rating should be Warm');
        }
    }*/
}